# Config file for automatic testing at travis-ci.org
sudo: false

language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install tox coverage codecov
  - coverage erase

# command to run tests, e.g. python setup.py test
script: tox -e py

after_success:
    - coverage combine
    # Report coverage results to codecov.io
    - codecov
