# coding: utf-8
from __future__ import unicode_literals


item_insert = [
    'item.itemUrl',
    'item.itemNumber',
    'item.itemName',
    'item.itemPrice',
    'item.genreId',
    'item.catalogId',
    'item.catalogIdExemptionReason',
    'item.images',
    'item.images.image',
    'item.images.image.imageUrl',
    'item.images.image.imageAlt',
    'item.descriptionForPC',
    'item.descriptionForMobile',
    'item.descriptionForSmartPhone',
    'item.movieUrl',
    'item.options',
    'item.options.option',
    'item.options.option.optionName',
    'item.options.option.optionStyle',
    'item.options.option.optionValues',
    'item.options.option.optionValues.optionValue',
    'item.options.option.optionValues.optionValue.value',
    'item.tagIds',
    'item.tagIds.tagId',
    'item.catchCopyForPC',
    'item.catchCopyForMobile',
    'item.descriptionBySalesMethod',
    'item.isSaleButton',
    'item.isDocumentButton',
    'item.isInquiryButton',
    'item.isStockNoticeButton',
    'item.itemLayout',
    'item.isIncludedTax',
    'item.isIncludedPostage',
    'item.isIncludedCashOnDeliveryPostage',
    'item.displayPrice',
    'item.orderLimit',
    'item.postage',
    'item.postageSegment1',
    'item.postageSegment2',
    'item.isNoshiEnable',
    'item.isTimeSale',
    'item.timeSaleStartDateTime',
    'item.timeSaleEndDateTime',
    'item.isUnavailableForSearch',
    'item.limitedPasswd',
    'item.isAvailableForMobile',
    'item.isDepot',
    'item.detailSellType',
    'item.releaseDate',
    'item.point',
    'item.point.pointRate',
    'item.point.pointRateStart',
    'item.point.pointRateEnd',
    'item.itemInventory',
    'item.itemInventory.inventoryType',
    'item.itemInventory.inventories',
    'item.itemInventory.inventories.inventory',
    'item.itemInventory.inventories.inventory.inventoryCount',
    'item.itemInventory.inventories.inventory.childNoVertical',
    'item.itemInventory.inventories.inventory.childNoHorizontal',
    'item.itemInventory.inventories.inventory.optionNameVertical',
    'item.itemInventory.inventories.inventory.optionNameHorizontal',
    'item.itemInventory.inventories.inventory.isBackorderAvailable',
    'item.itemInventory.inventories.inventory.normalDeliveryDateId',
    'item.itemInventory.inventories.inventory.backorderDeliveryDateId',
    'item.itemInventory.inventories.inventory.isBackorder',
    'item.itemInventory.inventories.inventory.isRestoreInventoryFlag',
    'item.itemInventory.inventories.inventory.images',
    'item.itemInventory.inventories.inventory.images.image',
    'item.itemInventory.inventories.inventory.images.image.imageUrl',
    'item.itemInventory.inventories.inventory.tagIds',
    'item.itemInventory.inventories.inventory.tagIds.tagId',
    'item.itemInventory.verticalName',
    'item.itemInventory.horizontalName',
    'item.itemInventory.inventoryQuantityFlag',
    'item.itemInventory.inventoryDisplayFlag',
    'item.asurakuDeliveryId',
    'item.sizeChartLinkCode',
    'item.reviewDisp',
    'item.medicine',
    'item.medicine.medCaption',
    'item.medicine.medAttention',
    'item.displayPriceId',
    'item.categories',
    'item.categories.categoryInfo',
    'item.categories.categoryInfo.categorySetManageNumber',
    'item.categories.categoryInfo.categoryId',
    'item.categories.categoryInfo.isPluralItemPage',
    'item.itemWeight',
    'item.layoutCommonId',
    'item.layoutMapId',
    'item.textSmallId',
    'item.lossLeaderId',
    'item.textLargeId',
]

item_update = [

]

item_delete = [

]

items_update = [

]
